name: Build WiX Toolset v6

on:
  push:
    branches:
      - dotnet8
    tags:
      - v**
  pull_request:
    branches:
      - dotnet8
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    name: Build
    runs-on: windows-2022
    env:
      RepoOrg: ${{ github.repository_owner }}
      SignBuild: ${{ startsWith(github.ref, 'refs/tags/v') }}
      WixOfficialBuild: ${{ github.repository_owner == 'wixtoolset' && startsWith(github.ref, 'refs/tags/v') }}
    permissions:
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure automated logging and crash dumps
        shell: cmd
        run: |
          reg add HKLM\Software\Policies\Microsoft\Windows\Installer /t REG_SZ /v Logging /d voicewarmupx /f
          reg add HKLM\Software\WOW6432Node\Policies\Microsoft\Windows\Installer /t REG_SZ /v Logging /d voicewarmupx /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" /t REG_EXPAND_SZ /v DumpFolder /d "%CD%\build\logs\crashdumps" /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" /t REG_DWORD /v DumpCount /d 10 /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" /t REG_DWORD /v DumpType /d 1 /f
          reg add "HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\Windows Error Reporting\LocalDumps" /t REG_EXPAND_SZ /v DumpFolder /d "%CD%\build\logs\crashdumps" /f
          reg add "HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\Windows Error Reporting\LocalDumps" /t REG_DWORD /v DumpCount /d 10 /f
          reg add "HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\Windows Error Reporting\LocalDumps" /t REG_DWORD /v DumpType /d 1

      - name: List installed SDKs
        shell: pwsh
        run:   dotnet --list-sdks

      - name: Install sign tool
        if: ${{ env.SignBuild == 'true' }}
        shell: cmd
        run: dotnet tool install --tool-path build\.tools sign --version 0.9.1-beta.24170.3

      - name: Login via Azure CLI
        if: ${{ env.SignBuild == 'true' }}
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build wix6
        shell: cmd
        run: ./src/build_official.cmd
        env:
          RuntimeTestsEnabled: true
          SigningKeyVaultUri: ${{ env.SignBuild == 'true' && 'https://lacssigningkeyvault.vault.azure.net/' || '' }}
          SigningTenantId: ${{ env.SignBuild == 'true' && secrets.TENANT_ID || '' }}
          SigningClientId: ${{ env.SignBuild == 'true' && secrets.APPLICATION_CLIENT_ID || '' }}
          SigningClientSecret: ${{ env.SignBuild == 'true' && secrets.CLIENT_SECRET || '' }}
          SigningCertName: ${{ env.SignBuild == 'true' && 'GlobalSign-Code-Signing-Certificate-NC' || '' }}

      - name: Validate test results
        if: ${{ !cancelled() }}
        shell: cmd
        run: |
          if exist src\testresultfilelist.txt (
            7z a build\testresults.zip @src\testresultfilelist.txt
          ) else (
            echo No testresultfilelist.txt found, skipping.
          )

      - name: Save build
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: build/artifacts/

      - name: Collect integration test logs
        if: ${{ !cancelled() }}
        shell: cmd
        run: 7z a "build\logs\test_burn_%GITHUB_RUN_ID%.zip" "%TEMP%\*.log" "%TEMP%\..\*.log"

      - name: Export Application event log
        if: ${{ !cancelled() }}
        shell: cmd
        run: wevtutil epl Application build\logs\Application.evtx /q:"Event/System/TimeCreated[timediff(@SystemTime) <= 86400000]"

      - name: Export System event log
        if: ${{ !cancelled() }}
        shell: cmd
        run: wevtutil epl System build\logs\System.evtx /q:"Event/System/TimeCreated[timediff(@SystemTime) <= 86400000]"

      # Do NOT publish logs on signed builds as they may contain secrets
      - name: Save logs
        if: ${{ env.SignBuild != 'true' && !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: logs_${{ github.run_id }}
          path: build/logs/

      - name: Push to GitHub Packages
        if: ${{ github.event_name == 'push' }}
        run: dotnet nuget push "build/artifacts/**/*.nupkg" --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
